version: '3.8'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_app
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    networks:
      - app_network
    depends_on:
      - db
  
  db:
    image: mysql:8.0
    container_name: db_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "9001:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    networks:
      - app_network
